// Events
export const FETCH_ALL_EVENTS_REQUEST = "FETCH_ALL_EVENTS_REQUEST";
export const FETCH_ALL_EVENTS_SUCCESS = "FETCH_ALL_EVENTS_SUCCESS";
export const FETCH_ALL_EVENTS_FAILURE = "FETCH_ALL_EVENTS_FAILURE";
export const FETCH_FEATURED_EVENTS_REQUEST = "FETCH_FEATURED_EVENTS_REQUEST";
export const FETCH_FEATURED_EVENTS_SUCCESS = "FETCH_FEATURED_EVENTS_SUCCESS";
export const FETCH_FEATURED_EVENTS_FAILURE = "FETCH_FEATURED_EVENTS_FAILURE";
export const ADD_EVENT_REQUEST = "ADD_EVENT_REQUEST";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAILURE = "ADD_EVENT_FAILURE";

// UI
export const SHOW_EVENT_DETAIL = "SHOW_EVENT_DETAIL";
export const SHOW_EVENT_FORM = "SHOW_EVENT_FORM";
export const SHOW_HOME = "SHOW_HOME";